### ISSUE TITLE
Create notebook to show how to navigate to a dataset of interest

### ISSUE THREAD

**Issue by potto216** [openpolicedata/opd-examples#1]

**Comment by potto216** [comment]
@sowdm can you think of anything not in [basic_usage.ipynb ](https://github.com/openpolicedata/opd-examples/blob/8ddb683639b43d0a42e07f89b29fc4ec558aa6fa/basic_usage.ipynb) that we should add to it or another notebook to close this issue?

**Comment by potto216** [comment]
@sowdm This is now in https://github.com/openpolicedata/opd-examples/blob/3-example-notebooks/finding_datasets.ipynb. If that looks okay I think this issue can be closed.

**Comment by sowdm** [comment]
@potto216 Notebooks look good. I made a few minor mods.
