### ISSUE TITLE
Move notebooks that are not focused on basic tasks using the release opd to an "offline" branch 

### ISSUE THREAD

**Issue by potto216** [openpolicedata/opd-examples#3]

**Comment by potto216** [comment]
@sowdm should we have notebook examples that require arcgis? I'm voting against it because of the installation difficulties.

**Comment by sowdm** [comment]
Do you meaning reading in data that requires the arcgis loader? arcgis currently installs automatically with our package so right now, it will be installed. If we wanted to remove arcgis dependence for the purposes of faster loading when running notesbooks online, we would have to maintain a separate code version without arcgis. We've talked about removing the arcgis dependency in the future, but that would be updating the arcgis loader to not use the arcgis package not removing the arcgis loader itself.

**Comment by potto216** [comment]
Oops, I meant geopandas. I ran into issues with arcgis when doing the setup and wrote about that by accident.  Geopandas requires an additional install unless we include it in the requirements.txt and I didn't know if it would effect the ability to have the notebooks live on Binder. I think we should have the majority of notebooks not require it, but include a small subset focused on plotting that use it.

**Comment by potto216** [comment]
@sowdm can you look over the main and archive branch and close this issue if everything looks okay?

**Comment by sowdm** [comment]
Agreed. No geopandas

**Comment by sowdm** [comment]
To be focused on basic tasks, I was thinking that the filenames should be actions. For example, the basic usage one might be split into something like finding datasets where queries are explored and exploring a dataset where usage of the Source class is explored. How does that sound?

For the basic_data_analysis_Virginia, that one does some very specific analysis of all the unknowns in Charlottesville. I think we need to generalize that one to do some more basic and universal analysis. I can help with that. Maybe the filename for this one should be about how pandas can be used to analyze the data that opd provides.

We might want a notebook that simply shows how to export data to CSV. It will be short but that's kind of the point.

**Comment by potto216** [comment]
@sowdm added the [offline branch](https://github.com/openpolicedata/opd-examples/tree/offline). Also added two basic tasks of finding and loading datasets. Just need to talk about the data analysis notebook.

**Comment by sowdm** [comment]
@potto216 Is this issue ready to be closed?

**Comment by potto216** [comment]
Yep I'll close it since https://github.com/openpolicedata/opd-examples/tree/offline is accessible.
